name: urban_flutter
description: Urban OS - Advanced City Intelligence Platform

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Network & API
  http: ^1.1.0
  http_parser: ^4.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Maps & Location
  # google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Media
  image_picker: ^1.0.5
  video_player: ^2.8.2
  chewie: ^1.7.5
  cached_network_image: ^3.3.1
  
  # Charts & Visualization (NEW!)
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^32.1.25
  
  # Animations (NEW!)
  lottie: ^3.3.2
  shimmer: ^3.0.0
  
  # Icons (NEW!)
  font_awesome_flutter: ^10.12.0
  flutter_staggered_animations: ^1.1.1
  
  # Utils
  intl: ^0.18.1
  speech_to_text: ^7.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.3
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
